
# Yellow
development:
  adapter: postgresql
  pool: 5
  timeout: 5000
  encoding: utf8
  database: dbfgc956i3r03e
  username: axbznqumhszall
  password: 3jPCgCNkk0GRQrqy54jUPURsYt
  host: ec2-50-19-233-111.compute-1.amazonaws.com

# cobalt
test:
  adapter: postgresql
  pool: 5
  timeout: 5000
  encoding: utf8
  database: d32tspk2luh2a6
  username: lbyfyxiglqiefh
  password: zwOXV5hwTAV0chWSnJAadMUOOB
  host: ec2-184-73-165-195.compute-1.amazonaws.com

# White
production:
  adapter: postgresql
  pool: 5
  timeout: 5000
  encoding: utf8
  database: dc1641kr65j8aj
  username: maydrtfvyjrbtj
  password: MEFJwaZ5CTB9RA3ckUYPACLfAK
  host: ec2-54-163-238-96.compute-1.amazonaws.com
