

development:
  adapter: postgresql
  pool: 5
  timeout: 5000
  encoding: utf8
  database: dc1641kr65j8aj
  username: maydrtfvyjrbtj
  password: MEFJwaZ5CTB9RA3ckUYPACLfAK
  host: ec2-54-163-238-96.compute-1.amazonaws.com

test:
  adapter: postgresql
  pool: 5
  timeout: 5000
  encoding: utf8
  database: d32tspk2luh2a6
  username: lbyfyxiglqiefh
  password: zwOXV5hwTAV0chWSnJAadMUOOB
  host: ec2-184-73-165-195.compute-1.amazonaws.com

production:
  adapter: postgresql
  pool: 5
  timeout: 5000
  encoding: utf8
  database: dc1641kr65j8aj
  username: maydrtfvyjrbtj
  password: MEFJwaZ5CTB9RA3ckUYPACLfAK
  host: ec2-54-163-238-96.compute-1.amazonaws.com
