

development:
  adapter: postgresql
  pool: 5
  timeout: 5000
  encoding: utf8
  database: d8sl52v2pm07a
  username: danmopscghfrwi
  password: FpSuD33o5Ly_ouRnhMPkAS8zdO
  host: ec2-54-243-187-196.compute-1.amazonaws.com

test:
  adapter: postgresql
  pool: 5
  timeout: 5000
  encoding: utf8
  database: d32tspk2luh2a6
  username: lbyfyxiglqiefh
  password: zwOXV5hwTAV0chWSnJAadMUOOB
  host: ec2-184-73-165-195.compute-1.amazonaws.com

test2:
  adapter: postgresql
  pool: 5
  timeout: 5000
  encoding: utf8
  database: booklyn-test
  username: booklyn
  password: 8at6v7gm
  host: localhost

production:
  adapter: postgresql
  pool: 5
  timeout: 5000
  encoding: utf8
  database: dc1641kr65j8aj
  username: maydrtfvyjrbtj
  password: MEFJwaZ5CTB9RA3ckUYPACLfAK
  host: ec2-54-163-238-96.compute-1.amazonaws.com
