shoboi:
    root: http://cal.syoboi.jp
    search: http://cal.syoboi.jp/find?sd=0&kw=
    title: http://cal.syoboi.jp/db.php?Command=TitleLookup&TID=*&LastUpdate=20150602_000000-
    schedule: http://cal.syoboi.jp/db.php?Command=ProgLookup&JOIN=SubTitles&Count=1&TID=

anikore:
    url: http://www.anikore.jp/chronicle/
    detail_url: http://www.anikore.jp/anime/
goo:
    api_key_2: 9f44e0022e49a2414c19d0689a687c44b0e85d603219e4f7042b6d57a668d678
    api_key: f1e955ecdad2c58490666bd77b11d0e655a38f828467245f6cd80ec53b611b1d
    url: https://labs.goo.ne.jp/api/morph

tfidf: 2.0
tvanimedouga:
    url: http://tvanimedouga.blog93.fc2.com/?all&p=


